version = 0.1

[default]
[default.global.parameters]
resolve_s3 = true

[default.build.parameters]
cached = true
parallel = true

[default.validate.parameters]
lint = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = false
fail_on_empty_changeset = false
region = "ap-northeast-1"

[default.package.parameters]
resolve_s3 = true

[dev]
[dev.deploy.parameters]
resolve_s3 = true
s3_prefix = "serverless-chat-dev"
stack_name = "serverless-chat-dev"
parameter_overrides = "Env=Dev"

[test]
[test.deploy.parameters]
resolve_s3 = true
s3_prefix = "serverless-chat-test"
stack_name = "serverless-chat-test"
parameter_overrides = "Env=Test"

[prod]
[prod.deploy.parameters]
resolve_s3 = true
s3_prefix = "serverless-chat-prod"
stack_name = "serverless-chat-prod"
parameter_overrides = "Env=Prod"