version = 0.1

[dev]
[dev.global.parameters]
region = "ap-northeast-1"
resolve_s3 = true
s3_prefix = "dreamgraph-dev"
stack_name = "dreamgraph-dev"
[dev.validate.parameters]
lint = true
[dev.build.parameters]
cached = true
[dev.deploy.parameters]
capabilities = ["CAPABILITY_IAM", "CAPABILITY_AUTO_EXPAND"]
confirm_changeset = false
fail_on_empty_changeset = false

parameter_overrides = "Env=Dev"
template = "backend/template.yaml"

[dev.sync.parameters]
capabilities = ["CAPABILITY_IAM", "CAPABILITY_AUTO_EXPAND"]
confirm_changeset = false
fail_on_empty_changeset = false

parameter_overrides = "Env=Dev"
template = "backend/template.yaml"

[test]
[test.global.parameters]
region = "ap-northeast-1"
s3_prefix = "dreamgraph-test"
stack_name = "dreamgraph-test"

[test.package.parameters]
template = "backend/template.yaml"

[test.deploy.parameters]
capabilities = ["CAPABILITY_IAM", "CAPABILITY_AUTO_EXPAND"]
confirm_changeset = false
fail_on_empty_changeset = false
parameter_overrides = "Env=Test"

[prod]
[prod.global.parameters]
region = "ap-northeast-1"
s3_prefix = "dreamgraph-prod"
stack_name = "dreamgraph-prod"

[prod.package.parameters]
template = "backend/template.yaml"

[prod.deploy.parameters]
capabilities = "CAPABILITY_AUTO_EXPAND"
confirm_changeset = false
fail_on_empty_changeset = false
parameter_overrides = "Env=Prod"

[cicd]
[cicd.deploy.parameters]
capabilities = ["CAPABILITY_IAM", "CAPABILITY_NAMED_IAM", "CAPABILITY_AUTO_EXPAND"]
confirm_changeset = false
s3_prefix = "dreamgraph-cicd"
stack_name = "dreamgraph-cicd"
template = ".cicd/template.yaml"
