version = 0.1

[dev]
[dev.validate.parameters]
lint = true
[dev.build.parameters]
cached = true
[dev.package.parameters]
resolve_s3 = true
[dev.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = false
fail_on_empty_changeset = false
region = "ap-northeast-1"

parameter_overrides = "Env=Dev"
resolve_s3 = true
s3_prefix = "serverless-chat-dev"
stack_name = "serverless-chat-dev"

[test]
[test.global.parameters]
resolve_s3 = true

[test.deploy.parameters]
confirm_changeset = false
fail_on_empty_changeset = false
region = "ap-northeast-1"

template = "template-test.yaml"
parameter_overrides = "Env=Test"
s3_prefix = "serverless-chat-test"
stack_name = "serverless-chat-test"

[prod]
[prod.global.parameters]
resolve_s3 = true

[prod.deploy.parameters]
confirm_changeset = false
fail_on_empty_changeset = false
region = "ap-northeast-1"

template = "template-prod.yaml"
parameter_overrides = "Env=Prod"
s3_prefix = "serverless-chat-prod"
stack_name = "serverless-chat-prod"
