AWSTemplateFormatVersion: 2010-09-09
Transform:
  - AWS::Serverless-2016-10-31

Parameters:
  AppName:
    Type: String
    Default: DreamGraph
  Env:
    Type: String
    AllowedValues:
      - Dev
      - Test
      - Prod

Resources:
  Auth:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./auth/template.yaml
      Parameters:
        AppName: !Ref AppName
        Env: !Ref Env
  Api:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./api/template.yaml
      Parameters:
        AppName: !Ref AppName
        Env: !Ref Env
        UserPoolId: !GetAtt Auth.Outputs.UserPoolId
        ProjectTableName: !GetAtt DB.Outputs.ProjectTableName
  DB:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./db/template.yaml
      Parameters:
        AppName: !Ref AppName
        Env: !Ref Env
  Host:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./host/template.yaml
      Parameters:
        AppName: !Ref AppName
        Env: !Ref Env

Outputs:
  UserPoolId:
    Value: !GetAtt Auth.Outputs.UserPoolId
  UserPoolClientId:
    Value: !GetAtt Auth.Outputs.UserPoolClientId
  ApiEndpoint:
    Value: !GetAtt Api.Outputs.ApiEndpoint
  ProjectTableName:
    Value: !GetAtt DB.Outputs.ProjectTableName
  WebS3BucketName:
    Value: !GetAtt Host.Outputs.WebS3BucketName
  CloudFrontDistributionId:
    Value: !GetAtt Host.Outputs.CloudFrontDistributionId
  CloudFrontDistributionDomainName:
    Value: !GetAtt Host.Outputs.CloudFrontDistributionDomainName
