AWSTemplateFormatVersion: 2010-09-09
Description: >-
  serverless chat backend
Transform:
  - AWS::Serverless-2016-10-31

Resources:
  GraphQLApi:
    Type: AWS::AppSync::GraphQLApi
    Properties:
      Name: my another chat appsync api
      AuthenticationType: API_KEY

  GraphQLApiKey:
    Type: AWS::AppSync::ApiKey
    Properties:
      ApiId: !GetAtt GraphQLApi.ApiId

  ForwardMessageDataSource:
    Type: AWS::AppSync::DataSource
    Properties:
      ApiId: !GetAtt GraphQLApi.ApiId
      Name: ForwardMessageDataSource
      Description: message forwarding datasource for subscription
      Type: NONE

  MutationSendMessage:
    Type: AWS::AppSync::Resolver
    DependsOn: Schema
    Properties:
      ApiId: !GetAtt GraphQLApi.ApiId
      TypeName: Mutation
      FieldName: sendMessage
      DataSourceName: !GetAtt ForwardMessageDataSource.Name
      Runtime:
        Name: APPSYNC_JS
        RuntimeVersion: 1.0.0
      CodeS3Location: ./graphql/forwardMessage.js

  Schema:
    Type: AWS::AppSync::GraphQLSchema
    Properties:
      ApiId: !GetAtt GraphQLApi.ApiId
      DefinitionS3Location: ./graphql/schema.graphql

Outputs:
  GraphQLApiId:
    Description: Api ID
    Value: !GetAtt GraphQLApi.ApiId
  GraphQLApiEndpoint:
    Description: Api url
    Value: !GetAtt GraphQLApi.GraphQLUrl
  GraphQLApiKey:
    Description: Api key
    Value: !GetAtt GraphQLApiKey.ApiKey
