AWSTemplateFormatVersion: 2010-09-09
Description: serverless chat pipeline IAM resources
Parameters:
  AppName:
    Type: String
    Default: ServerlessChat
  RoleName:
    Type: String
  CodeBuildProjectName:
    Type: String
    AllowedValues:
      - ServerlessChatBuildStack
      - ServerlessChatDeployStack
      - ServerlessChatDeployFrontEnd

Resources:
  CodeBuildServiceRolePolicy:
    Type: AWS::IAM::RolePolicy
    Properties:
      RoleName: !Sub ${RoleName}
      PolicyName: !Sub ${RoleName}-Policy
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
            Resource:
              - !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/${CodeBuildProjectName}
              - !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/${CodeBuildProjectName}:*
          - Effect: Allow
            Action:
              - s3:PutObject
              - s3:GetObject
              - s3:GetObjectVersion
              - s3:GetBucketAcl
              - s3:GetBucketLocation
            Resource:
              - !Sub arn:aws:s3:::codepipeline-${AWS::Region}-*
          - Effect: Allow
            Action:
              - codebuild:CreateReportGroup
              - codebuild:CreateReport
              - codebuild:UpdateReport
              - codebuild:BatchPutTestCases
              - codebuild:BatchPutCodeCoverages
            Resource:
              - !Sub arn:aws:codebuild:${AWS::Region}:${AWS::AccountId}:report-group/${CodeBuildProjectName}-*

Outputs:
  CodeBuildServiceRolePolicy:
    Value: !Ref CodeBuildServiceRolePolicy
