AWSTemplateFormatVersion: 2010-09-09
Description: serverless chat pipeline resources

Transform:
  - AWS::Serverless-2016-10-31

Parameters:
  AppName:
    Type: String
    Default: ServerlessChat
  ArtifactsBucketArn:
    Type: String

Resources:
  CodeBuildServiceRole:
    Type: AWS::IAM::Role
    Properties:
      Tags:
        - Key: Role
          Value: aws-sam-pipeline-codebuild-service-role
      RoleName: !Sub ${AppName}-CodeBuildServiceRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action: sts:AssumeRole
            Principal:
              Service:
                - codebuild.amazonaws.com
      Policies:
        - PolicyName: CodeBuildLogs
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource:
                  - !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/*'
        - PolicyName: CodeBuildArtifactsBucket
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:GetObjectVersion
                  - s3:PutObject
                Resource:
                  # - !Sub 'arn:aws:s3:::${PipelineArtifactsBucket}/*'
                  - !Sub arn:aws:s3:::codepipeline-${AWS::Region}-*
        - PolicyName: AssumeStagePipExecutionRoles
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: sts:AssumeRole
                Resource: '*'
                Condition:
                  StringEquals:
                    aws:ResourceTag/Role: pipeline-execution-role
  PipelineExecutionRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: !Sub ${AppName}-PipelineExecutionRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub arn:aws:iam::${AWS::AccountId}:root
            Action: sts:AssumeRole
            Condition:
              StringEquals:
                aws:PrincipalTag/Role: aws-sam-pipeline-codebuild-service-role
      Policies:
        - PolicyName: PipelineExecutionRolePermissions
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Action: iam:PassRole
                Effect: Allow
                Resource: !GetAtt PipelineCloudFormationExecutionRole.Arn
              - Action:
                  - cloudformation:CreateChangeSet
                  - cloudformation:DescribeChangeSet
                  - cloudformation:ExecuteChangeSet
                  - cloudformation:DeleteStack
                  - cloudformation:DescribeStackEvents
                  - cloudformation:DescribeStacks
                  - cloudformation:GetTemplate
                  - cloudformation:GetTemplateSummary
                  - cloudformation:DescribeStackResource
                Resource: '*'
                Effect: Allow
              - Action:
                  - s3:DeleteObject
                  - s3:GetObject*
                  - s3:PutObject*
                  - s3:GetBucket*
                  - s3:List*
                Resource:
                  - !Sub ${ArtifactsBucketArn}/*
                  - !Sub ${ArtifactsBucketArn}
                Effect: Allow

  PipelineCloudFormationExecutionRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: !Sub ${AppName}-PipelineCloudFormationExecutionRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: cloudformation.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: GrantCloudFormationFullAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Action: '*'
                Resource: '*'
                Effect: Allow
