AWSTemplateFormatVersion: 2010-09-09
Transform:
  - AWS::Serverless-2016-10-31

Parameters:
  AppName:
    Type: String
  Env:
    Type: String
    AllowedValues:
      - Dev
      - Test
      - Prod

Resources:
  ProjectTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${AppName}-${Env}-Project-Table
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: userId
          KeyType: 'HASH'
        - AttributeName: projectId
          KeyType: 'RANGE'
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: projectId
          AttributeType: S
        - AttributeName: title
          AttributeType: S
      LocalSecondaryIndexes:
        - IndexName: user-title-index
          KeySchema:
            - AttributeName: userId
              KeyType: HASH
            - AttributeName: title
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

Outputs:
  ProjectTableName:
    Value: !Ref ProjectTable
