name: deploy to test env

on:
  pull_request:
    branches: [ "main" ]

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  deploy-stacks:
    uses: ./.github/workflows/deploy-aws-stack.yml
    with:
      environment: prod

  deploy-frontend:
    needs: deploy-stacks
    uses: ./.github/workflows/deploy-frontend.yml
    with:
      environment: prod
